apiVersion: v2
name: lambda-karpenter
description: Karpenter cloud provider for Lambda Cloud GPU instances
type: application
version: v0.4.0
appVersion: "v0.4.0"
home: https://github.com/lambdal/lambda-karpenter
sources:
  - https://github.com/lambdal/lambda-karpenter
maintainers:
  - name: Eve Callicoat
