image:
  repository: apsu/lambda-karpenter
  tag: "0.1.9"
  pullPolicy: IfNotPresent

replicaCount: 1

serviceAccount:
  create: true
  name: ""
  annotations: {}

rbac:
  create: true

pdb:
  create: true
  maxUnavailable: 1

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

config:
  clusterName: ""
  apiTokenSecret:
    name: ""
    key: "token"
  apiBaseUrl: "https://cloud.lambda.ai"
  apiRps: 1
  launchMinIntervalSeconds: 5
  instanceTypeCacheTtl: 10m
  featureGates: "NodeRepair=false,ReservedCapacity=true,SpotToSpotConsolidation=false,NodeOverlay=false,StaticCapacity=false"

extraEnv: []
