{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "lambda-karpenter.fullname" . }}
rules:
  - apiGroups: ["", "apps", "coordination.k8s.io", "events.k8s.io", "policy", "rbac.authorization.k8s.io", "storage.k8s.io"]
    resources: ["nodes", "pods", "pods/eviction", "events", "leases", "serviceaccounts", "configmaps", "secrets", "persistentvolumes", "persistentvolumeclaims", "csinodes", "csidrivers", "storageclasses", "volumeattachments", "replicasets", "daemonsets", "statefulsets", "deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["karpenter.sh"]
    resources: ["nodeclaims", "nodepools", "nodeclasses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["karpenter.lambda.cloud"]
    resources: ["lambdanodeclasses", "lambdanodeclasses/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "lambda-karpenter.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "lambda-karpenter.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "lambda-karpenter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
