tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

toolkit:
  env:
    - name: CONTAINERD_SOCKET
      value: /run/k3s/containerd/containerd.sock

driver:
  enabled: false

daemonsets:
  tolerations:
    - key: "karpenter.sh/unregistered"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"

devicePlugin:
  env:
    - name: DEVICE_LIST_STRATEGY
      value: volume-mounts

node-feature-discovery:
  gc:
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
  worker:
    tolerations:
      - key: "karpenter.sh/unregistered"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
