apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  restartPolicy: Never
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  containers:
    - name: gpu-sleep
      image: ubuntu:22.04
      command: ["bash", "-lc", "sleep 3600"]
      resources:
        limits:
          nvidia.com/gpu: 1
